In [1]:
import numpy as np
from scipy.optimize import minimize
from sklearn import linear_model

In [2]:
n_s = 15
D = 10
d = 3

In [3]:
x_t = np.zeros((D,1))
index = np.random.choice([i for i in range(D)], d, False)
x_t[index] = 1
#x_t = np.random.uniform(0, 1, D)
x_t.sum(), x_t

(3.0, array([[ 0.],
        [ 0.],
        [ 1.],
        [ 1.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 1.]]))

In [6]:
A = np.zeros([D, n_s])

for j in range(n_s):
    index = np.random.choice([i for i in range(D)], d, False)
    A[index, j] = 1
A, A.shape, np.linalg.matrix_rank(A)

(array([[ 0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,
          0.,  0.],
        [ 0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
          0.,  0.],
        [ 1.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,
          0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
          1.,  0.],
        [ 0.,  1.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,
          0.,  0.],
        [ 0.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
          1.,  1.],
        [ 0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
          0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,
          0.,  1.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,
          1.,  1.]]), (10, 15), 10)

In [7]:
x_t = A[:, np.random.randint(0, n_s)]
#for i in range(n_s): print(np.linalg.norm(x_t - A[:,i]))

In [8]:
b = x_t.reshape(D,1)
#print(b)

In [40]:
def f(x):
    return np.linalg.norm(A.dot(x) - b)

def make_eq1():
    return lambda x: np.dot(np.ones(x.T.shape), x) - 1

def make_ineq(i, n_s):
    A = np.zeros([n_s, n_s])
    A[i,i] = 1
    return lambda x: np.dot(np.ones([1, n_s]), np.dot(A, x))

def makeConsIneq(n_s):
    f = []
    for i in range(n_s):
        f.append(make_ineq(i, n_s))
    f.append(make_eq1())
    return f

In [70]:
cons_funs = makeConsIneq(n_s)

cons = [{"type": "ineq", "fun": func} if i < n_s-1 else {"type": "eq", "fun": func} for i, func in enumerate(cons_funs)]
x = np.array([1 for i in range(n_s)]).reshape([n_s, 1])

result = minimize(f, x0=x, constraints=cons, method="SLSQP")
print(result)
#for i in range(n_s): print(result["x"][i])
print(np.var(result["x"]), np.max(result["x"]), np.min(result["x"]), np.sum(result["x"]))

     fun: 4.587768669092099
     jac: array([ 0.01091903,  0.0102824 ,  0.01068598,  0.010539  ,  0.11437184,
        0.01017755,  0.0104546 ,  0.01007181,  0.01006925,  0.01091963,
        0.01100338,  0.00996351,  0.01006949,  0.0103901 ,  0.0102818 ])
 message: 'Optimization terminated successfully.'
    nfev: 194
     nit: 11
    njev: 11
  status: 0
 success: True
       x: array([  7.09294072e-03,   6.88806134e-02,   1.76521109e-01,
         1.08701013e-01,  -2.60208521e-18,   4.38724029e-02,
         2.24587730e-01,   2.21128834e-01,   2.31574151e-02,
         4.04255630e-02,   6.43567665e-04,   3.08913837e-02,
         3.33195051e-02,   2.07779224e-02,   0.00000000e+00])
0.00580221913116 0.224587730141 -2.60208521397e-18 1.0


In [68]:
x_opt1 = np.array(result["x"])
np.linalg.norm(A.dot(x_opt1) - b), x_opt1.sum()

(4.5877684920682071, 1.0)

In [71]:
cons_funs = makeConsIneq(n_s)

cons = [{"type": "ineq", "fun": func} if i < n_s-1 else {"type": "eq", "fun": func} for i, func in enumerate(cons_funs)]
x = np.array([0 for i in range(n_s)]).reshape([n_s, 1])

result = minimize(f, x0=x, constraints=cons, method="SLSQP")
print(result)
#for i in range(n_s): print(result["x"][i])
print(np.var(result["x"]), np.max(result["x"]), np.min(result["x"]), np.sum(result["x"]))

     fun: 4.587768492068207
     jac: array([ 0.01042622,  0.00931275,  0.01071423,  0.01055318,  0.11353081,
        0.01017451,  0.01087922,  0.01030022,  0.00990456,  0.00925165,
        0.01010019,  0.01003027,  0.0094685 ,  0.01075733,  0.01048738])
 message: 'Optimization terminated successfully.'
    nfev: 196
     nit: 11
    njev: 11
  status: 0
 success: True
       x: array([  2.91835462e-03,   8.17780455e-02,   1.64588795e-01,
         1.15758117e-01,  -4.93534338e-17,   3.30110835e-02,
         2.17571675e-01,   2.09366024e-01,   1.07207369e-02,
         3.93724493e-02,   5.23527358e-03,   5.44422193e-02,
         2.20049994e-02,   4.32322277e-02,   0.00000000e+00])
0.00531932945814 0.217571674923 -4.93534338107e-17 1.0


In [66]:
x_opt2 = np.array(result["x"])
np.linalg.norm(A.dot(x_opt2) - b), x_opt2.sum()

(4.5877684920682071, 1.0)

In [65]:
print(x_opt1)
print(x_opt2)

[  7.09294072e-03   6.88806134e-02   1.76521109e-01   1.08701013e-01
  -2.60208521e-18   4.38724029e-02   2.24587730e-01   2.21128834e-01
   2.31574151e-02   4.04255630e-02   6.43567665e-04   3.08913837e-02
   3.33195051e-02   2.07779224e-02   0.00000000e+00]
[  2.91835462e-03   8.17780455e-02   1.64588795e-01   1.15758117e-01
  -4.93534338e-17   3.30110835e-02   2.17571675e-01   2.09366024e-01
   1.07207369e-02   3.93724493e-02   5.23527358e-03   5.44422193e-02
   2.20049994e-02   4.32322277e-02   0.00000000e+00]


In [76]:
LA = np.zeros([n_s+1+n_s, n_s+1+n_s])
for i in range(n_s+1+n_s):
    if i < n_s:
        for j in range(n_s+1+n_s):
            if j < n_s:
                LA[i,j] = 2*np.dot(A[:,i], A[:,j])
            elif j == n_s:
                LA[i,j] = -1
            elif j > n_s:
                LA[i,j] = 1 if i == (j - (n_s+1)) else 0
                
    elif i == n_s:
        LA[i,0:n_s] = 1
    elif i > n_s:
        LA[i, i-(n_s+1)] = 1
        
LA

array([[ 6.,  4.,  0.,  2.,  0.,  2.,  0.,  2.,  2.,  4.,  0.,  2.,  4.,
         2.,  2., -1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.],
       [ 4.,  6.,  2.,  2.,  2.,  2.,  2.,  4.,  2.,  2.,  0.,  2.,  4.,
         2.,  2., -1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  6.,  2.,  4.,  2.,  2.,  2.,  2.,  0.,  2.,  2.,  2.,
         0.,  4., -1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.],
       [ 2.,  2.,  2.,  6.,  2.,  0.,  0.,  4.,  0.,  0.,  2.,  2.,  0.,
         2.,  0., -1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  4.,  2.,  6.,  0.,  2.,  2.,  2.,  0.,  2.,  0.,  2.,
         2.,  2., -1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.],
       [ 2.,  2.,  2.,  0.,  0.,  6.,  2.,  0.,  0.,  4.,  2.,  4.,  2.,
         2.,  2., -1.,  0.,

In [77]:
Lb = np.zeros([(n_s+1+n_s), 1])
for i in range(n_s+1):
    if i < n_s: Lb[i] = 2*np.dot(A[:,i], b)
    elif i == n_s: Lb[i] = 1
Lb

array([[ 0.],
       [ 2.],
       [ 4.],
       [ 2.],
       [ 6.],
       [ 0.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 0.],
       [ 2.],
       [ 0.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [78]:
Lx = np.linalg.solve(LA, Lb)
print(Lx)
print(Lx[0:n_s].sum())

[[ -3.22191164e-03]
 [  5.29953885e-02]
 [ -1.10215320e-02]
 [  8.26429910e-02]
 [  2.34205247e-02]
 [  7.83714960e-02]
 [  6.31466314e-02]
 [  2.04606583e-01]
 [  9.15870293e-02]
 [ -3.33238892e-02]
 [  0.00000000e+00]
 [  2.03321541e-01]
 [  0.00000000e+00]
 [  1.84793096e-01]
 [  0.00000000e+00]
 [ -8.49735779e+14]
 [ -8.49735779e+14]
 [ -8.49735779e+14]
 [ -8.49735779e+14]
 [ -8.49735779e+14]
 [ -8.49735779e+14]
 [ -8.49735779e+14]
 [ -8.49735779e+14]
 [ -8.49735779e+14]
 [ -8.49735779e+14]
 [ -8.49735779e+14]
 [ -8.49735779e+14]
 [ -8.49735779e+14]
 [ -8.49735779e+14]
 [ -8.49735779e+14]
 [ -8.49735779e+14]]
0.937317947879


In [93]:
LA = np.zeros([n_s+1, n_s+1])
for i in range(n_s+1):
    if i < n_s:
        for j in range(n_s+1):
            if j < n_s:
                LA[i,j] = A.T.dot(A)[i,j]
            elif j == n_s:
                LA[i,j] = -1
                
    elif i == n_s:
        LA[i,0:n_s] = 1
LA

array([[ 3.,  2.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  2.,  0.,  1.,  2.,
         1.,  1., -1.],
       [ 2.,  3.,  1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.,  0.,  1.,  2.,
         1.,  1., -1.],
       [ 0.,  1.,  3.,  1.,  2.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,
         0.,  2., -1.],
       [ 1.,  1.,  1.,  3.,  1.,  0.,  0.,  2.,  0.,  0.,  1.,  1.,  0.,
         1.,  0., -1.],
       [ 0.,  1.,  2.,  1.,  3.,  0.,  1.,  1.,  1.,  0.,  1.,  0.,  1.,
         1.,  1., -1.],
       [ 1.,  1.,  1.,  0.,  0.,  3.,  1.,  0.,  0.,  2.,  1.,  2.,  1.,
         1.,  1., -1.],
       [ 0.,  1.,  1.,  0.,  1.,  1.,  3.,  1.,  2.,  1.,  2.,  1.,  1.,
         1.,  1., -1.],
       [ 1.,  2.,  1.,  2.,  1.,  0.,  1.,  3.,  1.,  0.,  0.,  1.,  1.,
         1.,  1., -1.],
       [ 1.,  1.,  1.,  0.,  1.,  0.,  2.,  1.,  3.,  1.,  1.,  0.,  2.,
         0.,  2., -1.],
       [ 2.,  1.,  0.,  0.,  0.,  2.,  1.,  0.,  1.,  3.,  1.,  1.,  2.,
         1.,  1., -1.],
       [ 0.,  0.,  1.,  1.,  1

In [96]:
Lb = np.zeros([(n_s+1), 1])
for i in range(n_s+1):
    if i < n_s: Lb[i] = A.T.dot(b)[i,0]
    elif i == n_s: Lb[n_s] = 1
Lb

array([[ 0.],
       [ 1.],
       [ 2.],
       [ 1.],
       [ 3.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [101]:
Lx = np.linalg.solve(LA, Lb)
print(Lx, Lx[0:n_s].sum())
print(Lx[Lx<0])

[[ -7.54680249e-01]
 [  7.43647433e-01]
 [  4.57459527e-02]
 [  3.85882846e-01]
 [  1.11445495e+00]
 [ -1.87081470e-16]
 [ -3.68797404e-01]
 [ -3.85882846e-01]
 [  9.14881149e-01]
 [  9.03848333e-01]
 [ -5.46083746e-01]
 [  1.25487763e-01]
 [ -8.92815517e-01]
 [ -1.14454947e-01]
 [ -1.71233716e-01]
 [ -1.59264183e-16]] 1.0
[ -7.54680249e-01  -1.87081470e-16  -3.68797404e-01  -3.85882846e-01
  -5.46083746e-01  -8.92815517e-01  -1.14454947e-01  -1.71233716e-01
  -1.59264183e-16]


In [83]:
LA = np.zeros([n_s+n_s, n_s+n_s])
for i in range(n_s+n_s):
    if i < n_s:
        for j in range(n_s+n_s):
            if j < n_s:
                LA[i,j] = -2*np.dot(A[:,i], A[:,j])
            else:
                LA[i,j] = -1 if i == (j - (n_s)) else 0
                
    else:
        LA[i, i-(n_s)] = 1
        
LA

array([[-6., -4., -0., -2., -0., -2., -0., -2., -2., -4., -0., -2., -4.,
        -2., -2., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [-4., -6., -2., -2., -2., -2., -2., -4., -2., -2., -0., -2., -4.,
        -2., -2.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [-0., -2., -6., -2., -4., -2., -2., -2., -2., -0., -2., -2., -2.,
        -0., -4.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [-2., -2., -2., -6., -2., -0., -0., -4., -0., -0., -2., -2., -0.,
        -2., -0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [-0., -2., -4., -2., -6., -0., -2., -2., -2., -0., -2., -0., -2.,
        -2., -2.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [-2., -2., -2., -0., -0., -6., -2., -0., -0., -4., -2., -4., -2.,
        -2., -2.,  0.,  0.,  0.,  0.,  0., -1.,  0.,

In [84]:
Lb = np.zeros([(n_s+n_s), 1])
for i in range(n_s):
    Lb[i] = -2*np.dot(A[:,i], b)
Lb

array([[-0.],
       [-2.],
       [-4.],
       [-2.],
       [-6.],
       [-0.],
       [-2.],
       [-2.],
       [-2.],
       [-0.],
       [-2.],
       [-0.],
       [-2.],
       [-2.],
       [-2.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [30]:
Lx = np.linalg.solve(LA, Lb)
Lx, Lx[0:n_s].sum()

(array([[  2.53859841e-15],
        [  2.21360295e-15],
        [ -3.70867995e-15],
        [ -2.26950158e-15],
        [ -4.23682294e-16],
        [ -3.27071733e-15],
        [  4.62799994e-15],
        [  5.45468527e-16],
        [  2.95252012e-15],
        [  7.60454972e-15],
        [  4.18768430e-15],
        [ -5.92410735e-15],
        [  8.25823160e-16],
        [ -1.35383759e-15],
        [ -3.25541872e-15],
        [ -5.58790759e-15],
        [  5.47238001e-15],
        [  4.13614100e-15],
        [ -6.13188363e-15],
        [ -2.11174247e-15],
        [ -2.19606751e-15],
        [  1.95634808e-15],
        [ -2.93029153e-15],
        [ -2.05167852e-15],
        [ -6.07937576e-15],
        [ -2.86567819e-15],
        [ -3.53531017e-15],
        [  4.73635701e-15],
        [ -1.62525045e-15],
        [ -2.98772970e-15],
        [ -1.33003171e-15],
        [ -6.98004740e-16],
        [  1.37989723e-15],
        [  3.98637362e-17],
        [  1.09326979e-15],
        [  7.4630122

In [85]:
LA = np.zeros([n_s+1, n_s+1])
for i in range(n_s+1):
    if i < n_s:
        for j in range(n_s+1):
            if j < n_s:
                LA[i,j] = np.dot(A[:,i], A[:,j])
            elif j == n_s:
                LA[i,j] = 1
                
    elif i == n_s:
        LA[i,0:n_s] = 1
        
LA, LA.shape, np.linalg.matrix_rank(LA)

(array([[ 3.,  2.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  2.,  0.,  1.,  2.,
          1.,  1.,  1.],
        [ 2.,  3.,  1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.,  0.,  1.,  2.,
          1.,  1.,  1.],
        [ 0.,  1.,  3.,  1.,  2.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,
          0.,  2.,  1.],
        [ 1.,  1.,  1.,  3.,  1.,  0.,  0.,  2.,  0.,  0.,  1.,  1.,  0.,
          1.,  0.,  1.],
        [ 0.,  1.,  2.,  1.,  3.,  0.,  1.,  1.,  1.,  0.,  1.,  0.,  1.,
          1.,  1.,  1.],
        [ 1.,  1.,  1.,  0.,  0.,  3.,  1.,  0.,  0.,  2.,  1.,  2.,  1.,
          1.,  1.,  1.],
        [ 0.,  1.,  1.,  0.,  1.,  1.,  3.,  1.,  2.,  1.,  2.,  1.,  1.,
          1.,  1.,  1.],
        [ 1.,  2.,  1.,  2.,  1.,  0.,  1.,  3.,  1.,  0.,  0.,  1.,  1.,
          1.,  1.,  1.],
        [ 1.,  1.,  1.,  0.,  1.,  0.,  2.,  1.,  3.,  1.,  1.,  0.,  2.,
          0.,  2.,  1.],
        [ 2.,  1.,  0.,  0.,  0.,  2.,  1.,  0.,  1.,  3.,  1.,  1.,  2.,
          1.,  1.,  1.],
        [ 

In [86]:
Lb = np.zeros([(n_s+1), 1])
for i in range(n_s+1):
    if i < n_s: Lb[i] = np.dot(A[:,i], b)
    elif i == n_s: Lb[n_s] = 1
Lb

array([[ 0.],
       [ 1.],
       [ 2.],
       [ 1.],
       [ 3.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [87]:
Lx = np.linalg.solve(LA, Lb)
print(np.concatenate([A.dot(Lx[0:n_s]), b], axis=1))
print(Lx[0:n_s].sum())
print(Lx[0:n_s])

[[ -1.11022302e-16   0.00000000e+00]
 [ -1.66533454e-16   0.00000000e+00]
 [  1.00000000e+00   1.00000000e+00]
 [  7.20755887e-18   0.00000000e+00]
 [  1.00000000e+00   1.00000000e+00]
 [  1.00000000e+00   1.00000000e+00]
 [  1.11022302e-16   0.00000000e+00]
 [  2.77555756e-17   0.00000000e+00]
 [ -2.22044605e-16   0.00000000e+00]
 [ -4.44089210e-16   0.00000000e+00]]
1.0
[[ -7.54680249e-01]
 [  7.43647433e-01]
 [  4.57459527e-02]
 [  3.85882846e-01]
 [  1.11445495e+00]
 [ -1.87081470e-16]
 [ -3.68797404e-01]
 [ -3.85882846e-01]
 [  9.14881149e-01]
 [  9.03848333e-01]
 [ -5.46083746e-01]
 [  1.25487763e-01]
 [ -8.92815517e-01]
 [ -1.14454947e-01]
 [ -1.71233716e-01]]


In [88]:
np.linalg.norm(A.dot(Lx[0:n_s]) - b)

6.4082775614681681e-16

In [90]:
A

array([[ 1.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,
         1.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.],
       [ 0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         0.,  1.],
       [ 0.,  1.,  1.,  0.,  1.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,
         0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,
         0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,
         0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,
         1.,  0.],
       [ 1.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,
         0.,  0.]])

In [92]:
lasso = linear_model.Lasso(0.1)